package com.dairy.milkroute.dto.request;

import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * One thing that happened on the road.
 *
 * <p>{@code clientEventId} is generated by the phone before the event is ever sent, and it
 * is what makes the offline story work: when signal comes back the phone replays everything
 * it has, because it cannot know which of them got through, and the unique index on this
 * column throws away what the server already holds.
 *
 * @param clientEventId  the phone's id for this event; the whole idempotency guarantee
 * @param type           one of the eleven driver event types
 * @param clientTs       when the phone says it happened; replay order comes from this, not
 *                       from arrival order
 * @param seq            which stop on the trip, for stop-scoped events
 * @param collections    per-farmer litres, for a COLLECTED
 * @param skipReason     why, on a STOP_SKIPPED
 */
public record DriverEventRequest(
        @NotNull UUID clientEventId,
        @NotBlank String type,
        @NotNull Instant clientTs,
        Integer seq,
        @Valid List<FarmerLitres> collections,
        String skipReason) {

    /**
     * What one farmer delivered.
     *
     * @param farmerCode the farmer, because milk is owed to a person and not to a place
     * @param litres     bounded at 500 here as well as by the CHECK constraint: a validation
     *                   message naming the bound is more use to a driver than a 500 from the
     *                   database
     */
    public record FarmerLitres(
            @NotBlank String farmerCode,
            @NotNull
            @DecimalMin(value = "0", message = "litres cannot be negative")
            @DecimalMax(value = "500", message = "litres must be 500 or less for one farmer")
            BigDecimal litres) {
    }
}
