-- V1 — baseline.
--
-- Flyway owns the schema (hard rule 5); Hibernate runs with ddl-auto: validate and never
-- generates DDL. This migration is intentionally empty: it establishes the baseline
-- version so that every real table arrives in a numbered, ordered migration behind it,
-- and it gives the schema history a starting point that predates any domain table.
--
-- Master data begins in V2__master_data.sql.
